version: '3'

services:
  postgres:
    image: postgres:13
    container_name: pg-docker
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5430:5432"
